<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SecretBase.Core\SecretBase.Core.csproj" />
    <ProjectReference Include="..\SecretBase.Platform.Abstractions\SecretBase.Platform.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SecretBase.Infrastructure.Tests" />
  </ItemGroup>

</Project>
